@isTest
public with sharing class ChatInsertTest {

   /* static testMethod void testChatUpdate() {
 		Account acc = new Account();
 		acc.FirstName = 'Stephen';
 		acc.LastName = 'Goldberg';
 		acc.PersonEmail = 'sgoldberg@statera.com';
 		insert acc;
 		
 		Lead lead = new Lead();
 		lead.FirstName = 'Stephen';
 		lead.LastName = 'Goldberg';
 		lead.Email = 'sgoldberg2@statera.com';
 		insert lead;
 		
 		
 		is1__Chat__c isChat = new is1__Chat__c();
 		isChat.is1__Email__c = 'sgoldberg@statera.com';
 		insert isChat;
 		
 		is1__Chat__c isChat2 = new is1__Chat__c();
 		isChat2.is1__Email__c = 'sgoldberg2@statera.com';
 		insert isChat2;
 		
 		      
       
       
       
       }*/

}