/**********************************************************************
Name: TestNotor_Webservice 
Copyright © notice: Nissan Motor Company.
======================================================
Purpose: Test class for Notor_Webservice.
======================================================
History:

VERSION     AUTHOR             DATE         DETAIL
1.0 -     Vivek Batham        06/17/2015    Created

***********************************************************************/

@isTest
private class TestNotor_Webservice {
    
    public static testmethod void test1(){
   
    Notor_Webservice.doGet(); 
    
    }
    
}